#!/bin/sh
files="/media/cdrom/custom"
apks="$files/apks/x86_64"
cp -r $files/bin/* /root/
cp -r $files/config /root/
#cp -r $files/apks /root
cp $files/keys/user-*.rsa.pub /etc/apk/keys/
echo "$files/apks" >> /etc/apk/repositories

# prepare network access with NetworkManager

# these apk files don't get detected correctly from the apk index, and have to be installed manually (in this order)
# this band-aid solution (manually installing the .apk files) is the only way i found around this issue
apk add --force-non-repository $apks/udev-init-scripts-*
#apk add --force-non-repository $apks/udev-init-scripts-openrc-*
apk add --force-non-repository $apks/eudev-openrc-*
apk add --force-non-repository $apks/eudev-*

# udev is needed by NetworkManager
setup-devd udev

apk add networkmanager
apk add networkmanager-cli

# same story, the exact error is: "package mentioned in index not found (try 'apk update')
apk add --force-non-repository $apks/networkmanager-openrc-*
apk add --force-non-repository $apks/dbus-openrc-*

rc-service networkmanager start

