#!/usr/bin/python3

from installer_settings import verbose, auto, mountpoint as mnt

from lib.core import system, get
from lib.wrappers import do, passwd, chroot, chdo, chadd, chdel, chrcadd, chrcstop, chrcstart, chrcdel, persist
from lib.utils import error, todo, confirm, unknown

import sys


# TODO: bootstrap alpine instead of cloning the installer


mode = get("install.mode")
if mode == "simple":
    do(f"BOOTLOADER=grub USE_EFI=1 setup-disk -m sys {mnt}")
elif mode == "full":
    # TODO: test doing the mkinitfs AFTER configuring alpine
    todo("install.mode")
    #chroot(mnt, "apk add mkinitfs")
else:
    unknown("install.mode")

#===============
# alpine settings
#===============

# keyboard
layout = get('settings.user.keyboard.layout')
variant = get('settings.user.keyboard.variant')
if variant == layout:
    chdo(mnt, f"setup-keymap {layout} {variant}")
else:
    chdo(mnt, f"setup-keymap {layout} {layout}-{variant}")
# hostname
hostname = get("settings.user.hostname")
chdo(mnt, f"setup-hostname {hostname}")
chdo(mnt, f"rc-service hostname restart")
# timezone
timezone = get("settings.user.timezone")
chdo(mnt, f"setup-timezone {timezone}")
# apk repos
mirror = get("settings.system.repository.apk.mirror")
switch = {
    "default": "-1",
    "fastest": "-f",
    "random": "-r",
}
args = switch[mirror]
if get("settings.system.repository.apk.community"):
    args += " -c"
chdo(mnt, f"setup-apkrepos {args}")
# this repository is added differently because the setup-apkrepos script does not have an option for test repos
if get("settings.system.repository.apk.edge-testing"):
    url = chdo(mnt, "cat /etc/apk/repositories | tail -n 1 | cut -d / -f 1-4")
    edge_testing = f"{url}/edge/testing"
    chdo(mnt, f"echo {edge_testing} >> /etc/apk/repositories")

# TODO: move this after chdo

# main user
username = get("settings.user.username")
password = get("settings.user.password")
fullname = get("settings.user.fullname")
# -a: admin (using this installs doas automatically)
# -g: groups
chdo(mnt, f"""setup-user -a -g 'audio video netdev' -f "{fullname}" "{username}" """)
# networkmanager uses the plugdev group for rootless interface management
if "networkmanager" in get("features.system"):
    chdo(mnt, f"adduser {username} plugdev")

# set the password for the user
# TODO: replace "echo |" with stdin=
chroot(mnt, "chpasswd", stdin=f"{username}:{password}")
#chdo(mnt, f'echo "{username}:{password}" | chpasswd')
persist(f"/home/{username}")

# lock root account
chdo(mnt, "passwd -l root")

