#!/usr/bin/python3
from lib.wrappers import do
from checks import check_dependencies, check_compat()

check_dependencies()
check_compat()

# partition
do("apk add cryptsetup lvm2 lsblk btrfs-progs e2fsprogs")
# install-alpine
do("apk add parted wipefs arch-install-scripts")
