# system parameters
# this config is made to match my preferences
# the "default" values in comments are the default values for Alpine Linux
# (and what the real default config should be once i'm not the only user anymore)

verbose: true


system:
  keyboard:
    # default: us
    layout: fr
    # default: us
    variant: fr-bepo
  # default: localhost
  hostname: alpine
  # default: UTC
  timezone: Europe/Paris
  repository:
    apk:
      # mirror: default | fastest | random
      mirror: default
      community: true
      # edge/testing repository (needed for riverwm)
      edge-testing: false
  user:
    username: user
    password: user
    fullname: user

  # add the doc packages when available
  man: true
  # use the Guix package manager when available
  guix: true
  # system services
  # disabling them is probably a bad idea
  services:
    networkmanager: true
    seedrng: true
    crond: true
    acpid: true


graphics:
  # preset: river | xfce | none
  # installing multiple graphical interfaces is not supported
  preset: river
  options:
    river:
      # launcher: wofi | bemenu
      launcher: bemenu
      # bar: waybar | none
      bar: waybar
      # background: swaybg | none
      background: swaybg
      # login: greetd-wlgreet | none
      login: greetd-wlgreet
      # terminal: foot | none
      terminal: foot
      # explorer: thunar | none
      explorer: thunar

services:
  # ssh: openssh | none
  ssh: openssh
  polkit: true
  udisks2: true

packages:
  vim: true
  nano: false
  firefox: true
  btop: false
  yq: true

